version: '3.8'

services:
  graphql-mcp-server:
    build: .
    image: graphql-mcp-server:latest
    container_name: graphql-mcp-server
    
    # For stdio transport (default)
    stdin_open: true
    tty: true
    
    # For HTTP transport, uncomment these lines:
    # ports:
    #   - "8080:8080"
    # command: ["node", "src/index.js", "--transport", "http", "--port", "8080"]
    
    # Environment variables (if needed)
    environment:
      - NODE_ENV=production
      # Uncomment to enable bearer token authentication for MCP requests
      # - AUTH_TOKEN=your-secret-token-here
    
    # Mount config file if using external configuration
    volumes:
      - ./expose.yaml:/app/expose.yaml:ro
    
    # Restart policy
    restart: unless-stopped
    
    # Resource limits (adjust as needed)
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M